sudo: required
services:
  - docker

before_install:
  - docker build -t kokolocco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kokolocco/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t client ./client
  - docker build -t server ./server
  - docker build -t nginx ./nginx
  - docker build -t worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kokolocco/multi_container:client
  - docker push kokolocco/multi_container:server
  - docker push kokolocco/multi_container:nginx
  - docker push kokolocco/multi_container:worker
