sudo: required
services:
  - docker

before_install:
  - docker build -t kokolocco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kokolocco/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t kokolocco/multicont_client ./client
  - docker build -t kokolocco/multicont_server ./server
  - docker build -t kokolocco/multicont_nginx ./nginx
  - docker build -t kokolocco/multicont_worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kokolocco/multicont_client
  - docker push kokolocco/multicont_server
  - docker push kokolocco/multicont_nginx
  - docker push kokolocco/multicont_worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app:   Multicontainer
  env: Multicontainer-env
  bucket_name: elasticbeanstalk-us-east-1-600270412190
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



